package com.babytracker.export.data

import androidx.room.withTransaction
import com.babytracker.data.local.BabyTrackerDatabase
import com.babytracker.data.local.entity.BottleFeedEntity
import com.babytracker.data.local.entity.BreastfeedingEntity
import com.babytracker.data.local.entity.DiaperEntity
import com.babytracker.data.local.entity.DoctorVisitEntity
import com.babytracker.data.local.entity.GrowthMeasurementEntity
import com.babytracker.data.local.entity.MilestoneEntity
import com.babytracker.data.local.entity.MilkBagEntity
import com.babytracker.data.local.entity.PumpingEntity
import com.babytracker.data.local.entity.SleepEntity
import com.babytracker.data.local.entity.VaccineEntity
import com.babytracker.data.local.entity.VisitQuestionEntity
import com.babytracker.export.domain.BackupImporter
import com.babytracker.export.domain.ImportCounts
import com.babytracker.export.domain.model.BackupData
import com.babytracker.domain.model.toSleepTypeOrNull
import com.babytracker.manager.DoctorVisitReminderScheduler
import com.babytracker.manager.VaccineReminderScheduler
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class BackupImporterImpl @Inject constructor(
    private val db: BabyTrackerDatabase,
    private val vaccineReminderScheduler: VaccineReminderScheduler,
    private val doctorVisitReminderScheduler: DoctorVisitReminderScheduler,
) : BackupImporter {

    override suspend fun merge(data: BackupData): ImportCounts {
        val counts = db.withTransaction {
            val bf = mergeBreastfeeding(data)
            val sleep = mergeSleep(data)
            val (pumpInserted, pumpIdMap) = mergePumping(data)
            val bags = mergeMilkBags(data, pumpIdMap)
            val bottles = mergeBottleFeeds(data)
            val growth = mergeGrowth(data)
            val milestones = mergeMilestones(data)
            val diapers = mergeDiapers(data)
            val vaccines = mergeVaccines(data)
            val (visitsInserted, visitIdMap) = mergeDoctorVisits(data)
            val questions = mergeVisitQuestions(data, visitIdMap)
            ImportCounts(
                bf, sleep, pumpInserted, bags, bottles, growth, milestones, diapers, vaccines,
                doctorVisitsInserted = visitsInserted,
                visitQuestionsInserted = questions,
            )
        }
        // Re-arm reminders only after the transaction commits, so imported future scheduled
        // rows get their alarms. rescheduleAll() cancels stale alarms then re-arms from the
        // now-persisted rows; it is a no-op-safe call when nothing future remains.
        vaccineReminderScheduler.rescheduleAll()
        doctorVisitReminderScheduler.rescheduleAll()
        return counts
    }

    /**
     * Dedup visits by [date, providerName, createdAt]. Returns (insertedCount, oldId -> resolvedId)
     * for EVERY backup visit id — both newly-inserted and already-existing (deduped) — so attached
     * questions can re-link to the right parent regardless of whether it was new or pre-existing.
     */
    private suspend fun mergeDoctorVisits(data: BackupData): Pair<Int, Map<Long, Long>> {
        val existingByIdentity = db.doctorVisitDao().getAllVisitsOnce()
            .associate { it.identity() to it.id }
            .toMutableMap()
        val idMap = HashMap<Long, Long>()
        var inserted = 0
        for (v in data.doctorVisits) {
            val entity = DoctorVisitEntity(
                date = v.date, providerName = v.providerName, notes = v.notes,
                snapshotLabel = v.snapshotLabel, snapshotCreatedAt = v.snapshotCreatedAt,
                createdAt = v.createdAt,
            )
            val key = entity.identity()
            val dbId = existingByIdentity[key] ?: run {
                val newId = db.doctorVisitDao().insertVisit(entity)
                existingByIdentity[key] = newId
                inserted++
                newId
            }
            idMap[v.id] = dbId
        }
        return inserted to idMap
    }

    /**
     * Dedup questions by [text, createdAt]. Re-link [visitId] through the old->resolved visit map;
     * only fall back to the inbox (null) when no parent resolves (orphaned attachment).
     */
    private suspend fun mergeVisitQuestions(data: BackupData, visitIdMap: Map<Long, Long>): Int {
        val seen = db.doctorVisitDao().getAllQuestionsOnce().map { it.identity() }.toMutableSet()
        var inserted = 0
        for (q in data.visitQuestions) {
            val resolvedVisitId = q.visitId?.let { visitIdMap[it] }
            val entity = VisitQuestionEntity(
                text = q.text, answered = q.answered, visitId = resolvedVisitId, createdAt = q.createdAt,
            )
            if (seen.add(entity.identity())) {
                db.doctorVisitDao().insertQuestion(entity)
                inserted++
            }
        }
        return inserted
    }

    // Identity excludes the autogenerated id (same as the other trackers) and also doseLabel/notes,
    // so two genuinely identical shots are deduped on re-import regardless of cosmetic fields.
    private suspend fun mergeVaccines(data: BackupData): Int {
        val seen = db.vaccineDao().getAllOnce().map { it.identity() }.toMutableSet()
        var inserted = 0
        for (v in data.vaccines) {
            val entity = VaccineEntity(
                name = v.name, doseLabel = v.doseLabel, status = v.status,
                scheduledDate = v.scheduledDate, administeredDate = v.administeredDate,
                notes = v.notes, createdAt = v.createdAt,
            )
            if (seen.add(entity.identity())) {
                db.vaccineDao().insert(entity)
                inserted++
            }
        }
        return inserted
    }

    private suspend fun mergeDiapers(data: BackupData): Int {
        val seen = db.diaperDao().getAllOnce().map { it.identity() }.toMutableSet()
        var inserted = 0
        for (d in data.diapers) {
            val entity = DiaperEntity(
                timestamp = d.timestamp, type = d.type, notes = d.notes, createdAt = d.createdAt,
            )
            if (seen.add(entity.identity())) {
                db.diaperDao().insert(entity)
                inserted++
            }
        }
        return inserted
    }

    private suspend fun mergeGrowth(data: BackupData): Int {
        val seen = db.growthMeasurementDao().getAllOnce().map { it.identity() }.toMutableSet()
        var inserted = 0
        for (g in data.growth) {
            val entity = GrowthMeasurementEntity(
                takenAt = g.takenAtMs, type = g.type, valueCanonical = g.valueCanonical, notes = g.notes,
            )
            if (seen.add(entity.identity())) {
                db.growthMeasurementDao().insert(entity)
                inserted++
            }
        }
        return inserted
    }

    // Free-form moments have no natural key, so dedup by (title, date, time) tuple: a repeated
    // restore of the same backup won't duplicate moments the device already has.
    private suspend fun mergeMilestones(data: BackupData): Int {
        val seen = db.milestoneDao().getAllOnce().map { it.identity() }.toMutableSet()
        var inserted = 0
        for (m in data.milestones) {
            val entity = MilestoneEntity(
                title = m.title, dateEpochDay = m.dateEpochDay,
                timeMinuteOfDay = m.timeMinuteOfDay, photoUri = null, note = m.note,
            )
            if (seen.add(entity.identity())) {
                db.milestoneDao().insert(entity)
                inserted++
            }
        }
        return inserted
    }

    private suspend fun mergeBreastfeeding(data: BackupData): Int {
        val seen = db.breastfeedingDao().getAllSessionsOnce().map { it.identity() }.toMutableSet()
        var inserted = 0
        for (b in data.breastfeeding) {
            val entity = BreastfeedingEntity(
                startTime = b.startTime, endTime = b.endTime, startingSide = b.startingSide,
                switchTime = b.switchTime, notes = b.notes, pausedAt = b.pausedAt,
                pausedDurationMs = b.pausedDurationMs,
            )
            if (seen.add(entity.identity())) {
                db.breastfeedingDao().insertSession(entity)
                inserted++
            }
        }
        return inserted
    }

    private suspend fun mergeSleep(data: BackupData): Int {
        val existingByIdentity = db.sleepDao().getAllRecordsOnce()
            .associateBy { it.identity() }
            .toMutableMap()
        var inserted = 0
        for (s in data.sleep) {
            val entity = SleepEntity(
                startTime = s.startTime,
                endTime = s.endTime,
                sleepType = s.sleepType.toSleepTypeOrNull()?.name ?: s.sleepType,
                notes = s.notes,
                timezoneId = s.timezoneId,
            )
            val key = entity.identity()
            val existing = existingByIdentity[key]
            when {
                existing == null -> {
                    val newId = db.sleepDao().insertRecord(entity)
                    existingByIdentity[key] = entity.copy(id = newId)
                    inserted++
                }
                existing.timezoneId == null && entity.timezoneId != null -> {
                    val repaired = existing.copy(timezoneId = entity.timezoneId)
                    db.sleepDao().updateRecord(repaired)
                    existingByIdentity[key] = repaired
                }
            }
        }
        return inserted
    }

    /** Returns (insertedCount, backupPumpingId -> dbId) for EVERY backup pumping id. */
    private suspend fun mergePumping(data: BackupData): Pair<Int, Map<Long, Long>> {
        val existingByIdentity = db.pumpingDao().getAllSessionsOnce()
            .associate { it.identity() to it.id }
            .toMutableMap()
        val idMap = HashMap<Long, Long>()
        var inserted = 0
        for (p in data.pumping) {
            val entity = PumpingEntity(
                startTime = p.startTime, endTime = p.endTime, breast = p.breast,
                volumeMl = p.volumeMl, notes = p.notes, pausedAt = p.pausedAt,
                pausedDurationMs = p.pausedDurationMs,
            )
            val key = entity.identity()
            val dbId = existingByIdentity[key] ?: run {
                val newId = db.pumpingDao().insert(entity)
                existingByIdentity[key] = newId
                inserted++
                newId
            }
            idMap[p.id] = dbId
        }
        return inserted to idMap
    }

    private suspend fun mergeMilkBags(data: BackupData, pumpIdMap: Map<Long, Long>): Int {
        val existingByIdentity =
            db.milkBagDao().getAllBagsOnce().associateBy { it.identity() }.toMutableMap()
        var inserted = 0
        for (m in data.milkBags) {
            val remappedSource = m.sourceSessionId?.let { pumpIdMap[it] }
            val entity = MilkBagEntity(
                collectionDate = m.collectionDate, volumeMl = m.volumeMl,
                sourceSessionId = remappedSource, usedAt = m.usedAt, notes = m.notes,
                createdAt = m.createdAt,
            )
            val key = entity.identity()
            val existing = existingByIdentity[key]
            when {
                existing == null -> {
                    db.milkBagDao().insert(entity)
                    existingByIdentity[key] = entity
                    inserted++
                }
                existing.sourceSessionId == null && remappedSource != null -> {
                    val repaired = existing.copy(sourceSessionId = remappedSource)
                    db.milkBagDao().update(repaired)
                    existingByIdentity[key] = repaired
                }
            }
        }
        return inserted
    }

    /**
     * Inserts backup bottle feeds, skipping exact duplicates. A feed's [linkedMilkBagId] is a FK
     * to a milk bag, whose db id is reassigned on import, so we resolve it the same way milk bags
     * resolve their pumping source: backup bag id -> backup bag identity -> real db bag id. Runs
     * after [mergeMilkBags] so the referenced bags already exist. linkedMilkBagId is excluded from
     * identity so a feed differing only in its (reassigned) link is treated as the same feed.
     */
    private suspend fun mergeBottleFeeds(data: BackupData): Int {
        val seen = db.bottleFeedDao().getAllOnce().map { it.identity() }.toMutableSet()
        val bagBackupById = data.milkBags.associateBy { it.id }
        val dbBagIdByIdentity =
            db.milkBagDao().getAllBagsOnce().associate { it.identity() to it.id }
        var inserted = 0
        for (f in data.bottleFeeds) {
            val resolvedBagId = f.linkedMilkBagId
                ?.let { bagBackupById[it] }
                ?.let { dbBagIdByIdentity[it.toEntity().identity()] }
            val entity = BottleFeedEntity(
                clientId = UUID.randomUUID().toString(), timestamp = f.timestamp,
                volumeMl = f.volumeMl, type = f.type, linkedMilkBagId = resolvedBagId,
                notes = f.notes, createdAt = f.createdAt,
            )
            if (seen.add(entity.identity())) {
                db.bottleFeedDao().insert(entity)
                inserted++
            }
        }
        return inserted
    }

    // Identity keys: every persisted field except autogen id; sourceSessionId also excluded for
    // milk bags so a bag differing only in link source is treated as the same inventory item.
    private fun BreastfeedingEntity.identity() =
        listOf(startTime, endTime, startingSide, switchTime, notes, pausedAt, pausedDurationMs)
    private fun SleepEntity.identity() = listOf(startTime, endTime, sleepType, notes)
    private fun PumpingEntity.identity() =
        listOf(startTime, endTime, breast, volumeMl, notes, pausedAt, pausedDurationMs)
    private fun MilkBagEntity.identity() = listOf(collectionDate, volumeMl, usedAt, notes, createdAt)
    private fun BottleFeedEntity.identity() = listOf(timestamp, volumeMl, type, notes, createdAt)
    private fun GrowthMeasurementEntity.identity() = listOf(takenAt, type, valueCanonical, notes)
    private fun MilestoneEntity.identity() = listOf(title, dateEpochDay, timeMinuteOfDay, note)
    private fun DiaperEntity.identity() = listOf(timestamp, type, notes, createdAt)
    private fun VaccineEntity.identity() = listOf(name, status, scheduledDate, administeredDate, createdAt)
    private fun DoctorVisitEntity.identity() = listOf(date, providerName, createdAt)
    private fun VisitQuestionEntity.identity() = listOf(text, createdAt)
}
