package com.babytracker.navigation

object Routes {
    const val ONBOARDING = "onboarding"
    const val HOME = "home"
    const val BREASTFEEDING = "breastfeeding"
    const val BREASTFEEDING_HISTORY = "breastfeeding/history"
    const val BREASTFEEDING_SETTINGS = "breastfeeding/settings"
    const val FEEDING_HISTORY = "feeding/history"
    const val SLEEP_TRACKING = "sleep"
    const val SLEEP_HISTORY = "sleep/history"
    const val SLEEP_SCHEDULE = "sleep/schedule"
    const val SLEEP_SETTINGS = "sleep/settings"
    const val SETTINGS = "settings"
    const val FEATURES = "features"
    const val DESIGN_SYSTEM_PREVIEW = "design_system/preview"
    const val CONNECT_PARTNER = "connect_partner"
    const val PARTNER_DASHBOARD = "partner_dashboard"
    const val PARTNER_FEED_HISTORY = "partner_feed_history"
    const val MANAGE_SHARING = "manage_sharing"
    const val PUMPING = "pumping"
    const val PUMPING_HISTORY = "pumping/history"
    const val INVENTORY = "inventory"
    const val INVENTORY_SETTINGS = "inventory/settings"
    const val BOTTLE_FEED = "bottle_feed"
    const val DIAPER = "diaper"
    const val DIAPER_HISTORY = "diaper/history"
    const val VACCINE = "vaccine"
    const val GROWTH = "growth"
    const val MILESTONES = "milestones"
    const val MILESTONE_DETAIL_ARG = "milestoneId"
    const val MILESTONE_DETAIL = "milestones/{$MILESTONE_DETAIL_ARG}"
    const val TRENDS = "trends"

    fun milestoneDetail(id: Long): String = "milestones/$id"
}
