package com.babytracker.navigation

object Routes {
    const val ONBOARDING = "onboarding"
    const val HOME = "home"
    const val BREASTFEEDING = "breastfeeding"
    const val BREASTFEEDING_HISTORY = "breastfeeding/history"
    const val FEEDING_HISTORY = "feeding/history"
    const val SLEEP_TRACKING = "sleep"
    const val SLEEP_HISTORY = "sleep/history"
    const val SLEEP_SCHEDULE = "sleep/schedule"
    const val SETTINGS = "settings"
    const val DESIGN_SYSTEM_PREVIEW = "design_system/preview"
    const val CONNECT_PARTNER = "connect_partner"
    const val PARTNER_DASHBOARD = "partner_dashboard"
    const val PARTNER_FEED_HISTORY = "partner_feed_history"
    const val MANAGE_SHARING = "manage_sharing"
    const val PUMPING = "pumping"
    const val PUMPING_HISTORY = "pumping/history"
    const val INVENTORY = "inventory"
    const val INVENTORY_SETTINGS = "inventory/settings"
    const val BOTTLE_FEED = "bottle_feed"
    const val GROWTH = "growth"
    const val MILESTONES = "milestones"
}
